import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import styled from "styled-components";
import Layout from "../components/Layout/index";

const Container = styled.div`
  text-align: center;
`;

const Home: NextPage = () => {
  const { data: session } = useSession();
  
  return (
    <Layout>
      <>
        <Head>
          <title>Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
          {!session && <button onClick={() => signIn()}>Login</button>}
          {session && 
          <>
           <h1>Bem Vindo(a) {session.user?.name}!</h1>
           <button onClick={() => signOut()}>LogOut</button>
          </>
          }
        </Container>
      </>
    </Layout>
  );
};

export default Home;
