import type { NextPage } from "next";
import Head from "next/head";

import styled from "styled-components";
import Layout from "../components/Layout";

const Container = styled.div`
  text-align: center;
`;

const Home: NextPage = () => {
  return (
    <Layout>
      <>
        <Head>
          <title>Blog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
          <h1>Bem Vindo(a)!</h1>
        </Container>
      </>
    </Layout>
  );
};

export default Home;
